//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 09:50:18 AM GMT+03:00 
//


package abit.paket.delete;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Campaigns" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="CampaignID" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
 *                     &lt;element name="CampaignUID" type="{}TUID" maxOccurs="unbounded"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CompetitiveGroups" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="CompetitiveGroupID" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
 *                     &lt;element name="CompetitiveGroupUID" type="{}TUID" maxOccurs="unbounded"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InstitutionAchievements" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="InstitutionAchievementUID" type="{}TUID" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TargetOrganizations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TargetOrganizationUID" type="{}TUID" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Applications" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Application" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="ApplicationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RegistrationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EntranceTestResults" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="EntranceTestsResultID" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
 *                     &lt;element name="EntranceTestsResultUID" type="{}TUID" maxOccurs="unbounded"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ApplicationCommonBenefits" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="ApplicationCommonBenefitID" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
 *                     &lt;element name="ApplicationCommonBenefitUID" type="{}TUID" maxOccurs="unbounded"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Orders" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="OrdersOfAdmission" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="OrderOfAdmissionUID" type="{}TUID" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="OrdersOfException" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="OrderOfExceptionUID" type="{}TUID" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ApplicationsInOrders" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Application" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="ApplicationNumber" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;length value="50"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="RegistrationDate" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="UID" type="{}TUID" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "DataForDelete")
public class DataForDelete {

    @XmlElement(name = "Campaigns")
    protected DataForDelete.Campaigns campaigns;
    @XmlElement(name = "CompetitiveGroups")
    protected DataForDelete.CompetitiveGroups competitiveGroups;
    @XmlElement(name = "InstitutionAchievements")
    protected DataForDelete.InstitutionAchievements institutionAchievements;
    @XmlElement(name = "TargetOrganizations")
    protected DataForDelete.TargetOrganizations targetOrganizations;
    @XmlElement(name = "Applications")
    protected DataForDelete.Applications applications;
    @XmlElement(name = "EntranceTestResults")
    protected DataForDelete.EntranceTestResults entranceTestResults;
    @XmlElement(name = "ApplicationCommonBenefits")
    protected DataForDelete.ApplicationCommonBenefits applicationCommonBenefits;
    @XmlElement(name = "Orders")
    protected DataForDelete.Orders orders;
    @XmlElement(name = "ApplicationsInOrders")
    protected DataForDelete.ApplicationsInOrders applicationsInOrders;

    /**
     * Gets the value of the campaigns property.
     * 
     * @return
     *     possible object is
     *     {@link DataForDelete.Campaigns }
     *     
     */
    public DataForDelete.Campaigns getCampaigns() {
        return campaigns;
    }

    /**
     * Sets the value of the campaigns property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataForDelete.Campaigns }
     *     
     */
    public void setCampaigns(DataForDelete.Campaigns value) {
        this.campaigns = value;
    }

    /**
     * Gets the value of the competitiveGroups property.
     * 
     * @return
     *     possible object is
     *     {@link DataForDelete.CompetitiveGroups }
     *     
     */
    public DataForDelete.CompetitiveGroups getCompetitiveGroups() {
        return competitiveGroups;
    }

    /**
     * Sets the value of the competitiveGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataForDelete.CompetitiveGroups }
     *     
     */
    public void setCompetitiveGroups(DataForDelete.CompetitiveGroups value) {
        this.competitiveGroups = value;
    }

    /**
     * Gets the value of the institutionAchievements property.
     * 
     * @return
     *     possible object is
     *     {@link DataForDelete.InstitutionAchievements }
     *     
     */
    public DataForDelete.InstitutionAchievements getInstitutionAchievements() {
        return institutionAchievements;
    }

    /**
     * Sets the value of the institutionAchievements property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataForDelete.InstitutionAchievements }
     *     
     */
    public void setInstitutionAchievements(DataForDelete.InstitutionAchievements value) {
        this.institutionAchievements = value;
    }

    /**
     * Gets the value of the targetOrganizations property.
     * 
     * @return
     *     possible object is
     *     {@link DataForDelete.TargetOrganizations }
     *     
     */
    public DataForDelete.TargetOrganizations getTargetOrganizations() {
        return targetOrganizations;
    }

    /**
     * Sets the value of the targetOrganizations property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataForDelete.TargetOrganizations }
     *     
     */
    public void setTargetOrganizations(DataForDelete.TargetOrganizations value) {
        this.targetOrganizations = value;
    }

    /**
     * Gets the value of the applications property.
     * 
     * @return
     *     possible object is
     *     {@link DataForDelete.Applications }
     *     
     */
    public DataForDelete.Applications getApplications() {
        return applications;
    }

    /**
     * Sets the value of the applications property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataForDelete.Applications }
     *     
     */
    public void setApplications(DataForDelete.Applications value) {
        this.applications = value;
    }

    /**
     * Gets the value of the entranceTestResults property.
     * 
     * @return
     *     possible object is
     *     {@link DataForDelete.EntranceTestResults }
     *     
     */
    public DataForDelete.EntranceTestResults getEntranceTestResults() {
        return entranceTestResults;
    }

    /**
     * Sets the value of the entranceTestResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataForDelete.EntranceTestResults }
     *     
     */
    public void setEntranceTestResults(DataForDelete.EntranceTestResults value) {
        this.entranceTestResults = value;
    }

    /**
     * Gets the value of the applicationCommonBenefits property.
     * 
     * @return
     *     possible object is
     *     {@link DataForDelete.ApplicationCommonBenefits }
     *     
     */
    public DataForDelete.ApplicationCommonBenefits getApplicationCommonBenefits() {
        return applicationCommonBenefits;
    }

    /**
     * Sets the value of the applicationCommonBenefits property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataForDelete.ApplicationCommonBenefits }
     *     
     */
    public void setApplicationCommonBenefits(DataForDelete.ApplicationCommonBenefits value) {
        this.applicationCommonBenefits = value;
    }

    /**
     * Gets the value of the orders property.
     * 
     * @return
     *     possible object is
     *     {@link DataForDelete.Orders }
     *     
     */
    public DataForDelete.Orders getOrders() {
        return orders;
    }

    /**
     * Sets the value of the orders property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataForDelete.Orders }
     *     
     */
    public void setOrders(DataForDelete.Orders value) {
        this.orders = value;
    }

    /**
     * Gets the value of the applicationsInOrders property.
     * 
     * @return
     *     possible object is
     *     {@link DataForDelete.ApplicationsInOrders }
     *     
     */
    public DataForDelete.ApplicationsInOrders getApplicationsInOrders() {
        return applicationsInOrders;
    }

    /**
     * Sets the value of the applicationsInOrders property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataForDelete.ApplicationsInOrders }
     *     
     */
    public void setApplicationsInOrders(DataForDelete.ApplicationsInOrders value) {
        this.applicationsInOrders = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="ApplicationCommonBenefitID" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
     *           &lt;element name="ApplicationCommonBenefitUID" type="{}TUID" maxOccurs="unbounded"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "applicationCommonBenefitID",
        "applicationCommonBenefitUID"
    })
    public static class ApplicationCommonBenefits {

        @XmlElement(name = "ApplicationCommonBenefitID", type = Long.class)
        @XmlSchemaType(name = "unsignedInt")
        protected List<Long> applicationCommonBenefitID;
        @XmlElement(name = "ApplicationCommonBenefitUID")
        protected List<String> applicationCommonBenefitUID;

        /**
         * Gets the value of the applicationCommonBenefitID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the applicationCommonBenefitID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApplicationCommonBenefitID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public List<Long> getApplicationCommonBenefitID() {
            if (applicationCommonBenefitID == null) {
                applicationCommonBenefitID = new ArrayList<Long>();
            }
            return this.applicationCommonBenefitID;
        }

        /**
         * Gets the value of the applicationCommonBenefitUID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the applicationCommonBenefitUID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApplicationCommonBenefitUID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getApplicationCommonBenefitUID() {
            if (applicationCommonBenefitUID == null) {
                applicationCommonBenefitUID = new ArrayList<String>();
            }
            return this.applicationCommonBenefitUID;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Application" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="ApplicationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RegistrationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "application"
    })
    public static class Applications {

        @XmlElement(name = "Application", required = true)
        protected List<DataForDelete.Applications.Application> application;

        /**
         * Gets the value of the application property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the application property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApplication().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DataForDelete.Applications.Application }
         * 
         * 
         */
        public List<DataForDelete.Applications.Application> getApplication() {
            if (application == null) {
                application = new ArrayList<DataForDelete.Applications.Application>();
            }
            return this.application;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="ApplicationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RegistrationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Application {

            @XmlElement(name = "ApplicationNumber", required = true)
            protected String applicationNumber;
            @XmlElement(name = "RegistrationDate", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar registrationDate;

            /**
             * Gets the value of the applicationNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApplicationNumber() {
                return applicationNumber;
            }

            /**
             * Sets the value of the applicationNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApplicationNumber(String value) {
                this.applicationNumber = value;
            }

            /**
             * Gets the value of the registrationDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getRegistrationDate() {
                return registrationDate;
            }

            /**
             * Sets the value of the registrationDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setRegistrationDate(XMLGregorianCalendar value) {
                this.registrationDate = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Application" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="ApplicationNumber" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;length value="50"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="RegistrationDate" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="UID" type="{}TUID" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "application"
    })
    public static class ApplicationsInOrders {

        @XmlElement(name = "Application", required = true)
        protected List<DataForDelete.ApplicationsInOrders.Application> application;

        /**
         * Gets the value of the application property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the application property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApplication().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DataForDelete.ApplicationsInOrders.Application }
         * 
         * 
         */
        public List<DataForDelete.ApplicationsInOrders.Application> getApplication() {
            if (application == null) {
                application = new ArrayList<DataForDelete.ApplicationsInOrders.Application>();
            }
            return this.application;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="ApplicationNumber" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;length value="50"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="RegistrationDate" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="UID" type="{}TUID" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Application {

            @XmlElement(name = "ApplicationNumber")
            protected String applicationNumber;
            @XmlElement(name = "RegistrationDate")
            protected XMLGregorianCalendar registrationDate;
            @XmlElement(name = "UID")
            protected String uid;

            /**
             * Gets the value of the applicationNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApplicationNumber() {
                return applicationNumber;
            }

            /**
             * Sets the value of the applicationNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApplicationNumber(String value) {
                this.applicationNumber = value;
            }

            /**
             * Gets the value of the registrationDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getRegistrationDate() {
                return registrationDate;
            }

            /**
             * Sets the value of the registrationDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setRegistrationDate(XMLGregorianCalendar value) {
                this.registrationDate = value;
            }

            /**
             * Gets the value of the uid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUID() {
                return uid;
            }

            /**
             * Sets the value of the uid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUID(String value) {
                this.uid = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="CampaignID" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
     *           &lt;element name="CampaignUID" type="{}TUID" maxOccurs="unbounded"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "campaignID",
        "campaignUID"
    })
    public static class Campaigns {

        @XmlElement(name = "CampaignID", type = Long.class)
        @XmlSchemaType(name = "unsignedInt")
        protected List<Long> campaignID;
        @XmlElement(name = "CampaignUID")
        protected List<String> campaignUID;

        /**
         * Gets the value of the campaignID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the campaignID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCampaignID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public List<Long> getCampaignID() {
            if (campaignID == null) {
                campaignID = new ArrayList<Long>();
            }
            return this.campaignID;
        }

        /**
         * Gets the value of the campaignUID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the campaignUID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCampaignUID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCampaignUID() {
            if (campaignUID == null) {
                campaignUID = new ArrayList<String>();
            }
            return this.campaignUID;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="CompetitiveGroupID" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
     *           &lt;element name="CompetitiveGroupUID" type="{}TUID" maxOccurs="unbounded"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "competitiveGroupID",
        "competitiveGroupUID"
    })
    public static class CompetitiveGroups {

        @XmlElement(name = "CompetitiveGroupID", type = Long.class)
        @XmlSchemaType(name = "unsignedInt")
        protected List<Long> competitiveGroupID;
        @XmlElement(name = "CompetitiveGroupUID")
        protected List<String> competitiveGroupUID;

        /**
         * Gets the value of the competitiveGroupID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the competitiveGroupID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCompetitiveGroupID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public List<Long> getCompetitiveGroupID() {
            if (competitiveGroupID == null) {
                competitiveGroupID = new ArrayList<Long>();
            }
            return this.competitiveGroupID;
        }

        /**
         * Gets the value of the competitiveGroupUID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the competitiveGroupUID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCompetitiveGroupUID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCompetitiveGroupUID() {
            if (competitiveGroupUID == null) {
                competitiveGroupUID = new ArrayList<String>();
            }
            return this.competitiveGroupUID;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="EntranceTestsResultID" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
     *           &lt;element name="EntranceTestsResultUID" type="{}TUID" maxOccurs="unbounded"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entranceTestsResultID",
        "entranceTestsResultUID"
    })
    public static class EntranceTestResults {

        @XmlElement(name = "EntranceTestsResultID", type = Long.class)
        @XmlSchemaType(name = "unsignedInt")
        protected List<Long> entranceTestsResultID;
        @XmlElement(name = "EntranceTestsResultUID")
        protected List<String> entranceTestsResultUID;

        /**
         * Gets the value of the entranceTestsResultID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entranceTestsResultID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntranceTestsResultID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public List<Long> getEntranceTestsResultID() {
            if (entranceTestsResultID == null) {
                entranceTestsResultID = new ArrayList<Long>();
            }
            return this.entranceTestsResultID;
        }

        /**
         * Gets the value of the entranceTestsResultUID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entranceTestsResultUID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntranceTestsResultUID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getEntranceTestsResultUID() {
            if (entranceTestsResultUID == null) {
                entranceTestsResultUID = new ArrayList<String>();
            }
            return this.entranceTestsResultUID;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="InstitutionAchievementUID" type="{}TUID" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "institutionAchievementUID"
    })
    public static class InstitutionAchievements {

        @XmlElement(name = "InstitutionAchievementUID", required = true)
        protected List<String> institutionAchievementUID;

        /**
         * Gets the value of the institutionAchievementUID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the institutionAchievementUID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInstitutionAchievementUID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getInstitutionAchievementUID() {
            if (institutionAchievementUID == null) {
                institutionAchievementUID = new ArrayList<String>();
            }
            return this.institutionAchievementUID;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="OrdersOfAdmission" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="OrderOfAdmissionUID" type="{}TUID" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OrdersOfException" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="OrderOfExceptionUID" type="{}TUID" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Orders {

        @XmlElement(name = "OrdersOfAdmission")
        protected DataForDelete.Orders.OrdersOfAdmission ordersOfAdmission;
        @XmlElement(name = "OrdersOfException")
        protected DataForDelete.Orders.OrdersOfException ordersOfException;

        /**
         * Gets the value of the ordersOfAdmission property.
         * 
         * @return
         *     possible object is
         *     {@link DataForDelete.Orders.OrdersOfAdmission }
         *     
         */
        public DataForDelete.Orders.OrdersOfAdmission getOrdersOfAdmission() {
            return ordersOfAdmission;
        }

        /**
         * Sets the value of the ordersOfAdmission property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataForDelete.Orders.OrdersOfAdmission }
         *     
         */
        public void setOrdersOfAdmission(DataForDelete.Orders.OrdersOfAdmission value) {
            this.ordersOfAdmission = value;
        }

        /**
         * Gets the value of the ordersOfException property.
         * 
         * @return
         *     possible object is
         *     {@link DataForDelete.Orders.OrdersOfException }
         *     
         */
        public DataForDelete.Orders.OrdersOfException getOrdersOfException() {
            return ordersOfException;
        }

        /**
         * Sets the value of the ordersOfException property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataForDelete.Orders.OrdersOfException }
         *     
         */
        public void setOrdersOfException(DataForDelete.Orders.OrdersOfException value) {
            this.ordersOfException = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="OrderOfAdmissionUID" type="{}TUID" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "orderOfAdmissionUID"
        })
        public static class OrdersOfAdmission {

            @XmlElement(name = "OrderOfAdmissionUID", required = true)
            protected List<String> orderOfAdmissionUID;

            /**
             * Gets the value of the orderOfAdmissionUID property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the orderOfAdmissionUID property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOrderOfAdmissionUID().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getOrderOfAdmissionUID() {
                if (orderOfAdmissionUID == null) {
                    orderOfAdmissionUID = new ArrayList<String>();
                }
                return this.orderOfAdmissionUID;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="OrderOfExceptionUID" type="{}TUID" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "orderOfExceptionUID"
        })
        public static class OrdersOfException {

            @XmlElement(name = "OrderOfExceptionUID", required = true)
            protected List<String> orderOfExceptionUID;

            /**
             * Gets the value of the orderOfExceptionUID property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the orderOfExceptionUID property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOrderOfExceptionUID().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getOrderOfExceptionUID() {
                if (orderOfExceptionUID == null) {
                    orderOfExceptionUID = new ArrayList<String>();
                }
                return this.orderOfExceptionUID;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TargetOrganizationUID" type="{}TUID" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "targetOrganizationUID"
    })
    public static class TargetOrganizations {

        @XmlElement(name = "TargetOrganizationUID", required = true)
        protected List<String> targetOrganizationUID;

        /**
         * Gets the value of the targetOrganizationUID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the targetOrganizationUID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTargetOrganizationUID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getTargetOrganizationUID() {
            if (targetOrganizationUID == null) {
                targetOrganizationUID = new ArrayList<String>();
            }
            return this.targetOrganizationUID;
        }

    }

}
