//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 09:50:18 AM GMT+03:00 
//


package abit.paket.delete;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kk package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Login_QNAME = new QName("", "Login");
    private final static QName _Pass_QNAME = new QName("", "Pass");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kk
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataForDelete.Orders.OrdersOfException }
     * 
     */
    public DataForDelete.Orders.OrdersOfException createDataForDeleteOrdersOrdersOfException() {
        return new DataForDelete.Orders.OrdersOfException();
    }

    /**
     * Create an instance of {@link DataForDelete.InstitutionAchievements }
     * 
     */
    public DataForDelete.InstitutionAchievements createDataForDeleteInstitutionAchievements() {
        return new DataForDelete.InstitutionAchievements();
    }

    /**
     * Create an instance of {@link DataForDelete.TargetOrganizations }
     * 
     */
    public DataForDelete.TargetOrganizations createDataForDeleteTargetOrganizations() {
        return new DataForDelete.TargetOrganizations();
    }

    /**
     * Create an instance of {@link DataForDelete.CompetitiveGroups }
     * 
     */
    public DataForDelete.CompetitiveGroups createDataForDeleteCompetitiveGroups() {
        return new DataForDelete.CompetitiveGroups();
    }

    /**
     * Create an instance of {@link DataForDelete.ApplicationsInOrders.Application }
     * 
     */
    public DataForDelete.ApplicationsInOrders.Application createDataForDeleteApplicationsInOrdersApplication() {
        return new DataForDelete.ApplicationsInOrders.Application();
    }

    /**
     * Create an instance of {@link DataForDelete.ApplicationCommonBenefits }
     * 
     */
    public DataForDelete.ApplicationCommonBenefits createDataForDeleteApplicationCommonBenefits() {
        return new DataForDelete.ApplicationCommonBenefits();
    }

    /**
     * Create an instance of {@link DataForDelete.Applications.Application }
     * 
     */
    public DataForDelete.Applications.Application createDataForDeleteApplicationsApplication() {
        return new DataForDelete.Applications.Application();
    }

    /**
     * Create an instance of {@link DataForDelete }
     * 
     */
    public DataForDelete createDataForDelete() {
        return new DataForDelete();
    }

    /**
     * Create an instance of {@link DataForDelete.Applications }
     * 
     */
    public DataForDelete.Applications createDataForDeleteApplications() {
        return new DataForDelete.Applications();
    }

    /**
     * Create an instance of {@link DataForDelete.Orders }
     * 
     */
    public DataForDelete.Orders createDataForDeleteOrders() {
        return new DataForDelete.Orders();
    }

    /**
     * Create an instance of {@link DataForDelete.EntranceTestResults }
     * 
     */
    public DataForDelete.EntranceTestResults createDataForDeleteEntranceTestResults() {
        return new DataForDelete.EntranceTestResults();
    }

    /**
     * Create an instance of {@link DataForDelete.Campaigns }
     * 
     */
    public DataForDelete.Campaigns createDataForDeleteCampaigns() {
        return new DataForDelete.Campaigns();
    }

    /**
     * Create an instance of {@link DataForDelete.Orders.OrdersOfAdmission }
     * 
     */
    public DataForDelete.Orders.OrdersOfAdmission createDataForDeleteOrdersOrdersOfAdmission() {
        return new DataForDelete.Orders.OrdersOfAdmission();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link AuthData }
     * 
     */
    public AuthData createAuthData() {
        return new AuthData();
    }

    /**
     * Create an instance of {@link DataForDelete.ApplicationsInOrders }
     * 
     */
    public DataForDelete.ApplicationsInOrders createDataForDeleteApplicationsInOrders() {
        return new DataForDelete.ApplicationsInOrders();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Login")
    public JAXBElement<String> createLogin(String value) {
        return new JAXBElement<String>(_Login_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Pass")
    public JAXBElement<String> createPass(String value) {
        return new JAXBElement<String>(_Pass_QNAME, String.class, null, value);
    }

}
