//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 09:50:18 AM GMT+03:00 
//


package abit.paket.delete;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}AuthData"/>
 *         &lt;element ref="{}DataForDelete"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Root")
public class Root {

    @XmlElement(name = "AuthData", required = true)
    protected AuthData authData;
    @XmlElement(name = "DataForDelete", required = true)
    protected DataForDelete dataForDelete;

    /**
     * Gets the value of the authData property.
     * 
     * @return
     *     possible object is
     *     {@link AuthData }
     *     
     */
    public AuthData getAuthData() {
        return authData;
    }

    /**
     * Sets the value of the authData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthData }
     *     
     */
    public void setAuthData(AuthData value) {
        this.authData = value;
    }

    /**
     * Gets the value of the dataForDelete property.
     * 
     * @return
     *     possible object is
     *     {@link DataForDelete }
     *     
     */
    public DataForDelete getDataForDelete() {
        return dataForDelete;
    }

    /**
     * Sets the value of the dataForDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataForDelete }
     *     
     */
    public void setDataForDelete(DataForDelete value) {
        this.dataForDelete = value;
    }

}
