//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.13 at 12:57:22 PM GMT+03:00 
//


package abit.paket;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kkk package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kkk
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.OlympicsLevels.Olympic }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.OlympicsLevels.Olympic createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupEntranceTestItemsEntranceTestItemEntranceTestBenefitsEntranceTestBenefitItemOlympicsLevelsOlympic() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.OlympicsLevels.Olympic();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.EduDocuments }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.EduDocuments createPackageDataApplicationsApplicationApplicationDocumentsEduDocuments() {
        return new PackageData.Applications.Application.ApplicationDocuments.EduDocuments();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.EntranceTestResults.EntranceTestResult.ResultDocument }
     * 
     */
    public PackageData.Applications.Application.EntranceTestResults.EntranceTestResult.ResultDocument createPackageDataApplicationsApplicationEntranceTestResultsEntranceTestResultResultDocument() {
        return new PackageData.Applications.Application.EntranceTestResults.EntranceTestResult.ResultDocument();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.TargetOrganizations.TargetOrganization.CompetitiveGroupTargetItem }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.TargetOrganizations.TargetOrganization.CompetitiveGroupTargetItem createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupTargetOrganizationsTargetOrganizationCompetitiveGroupTargetItem() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.TargetOrganizations.TargetOrganization.CompetitiveGroupTargetItem();
    }

    /**
     * Create an instance of {@link PackageData.TargetOrganizations }
     * 
     */
    public PackageData.TargetOrganizations createPackageDataTargetOrganizations() {
        return new PackageData.TargetOrganizations();
    }

    /**
     * Create an instance of {@link TOlympicTotalDocument.Subjects }
     * 
     */
    public TOlympicTotalDocument.Subjects createTOlympicTotalDocumentSubjects() {
        return new TOlympicTotalDocument.Subjects();
    }

    /**
     * Create an instance of {@link TSchoolCertificateDocument.Subjects }
     * 
     */
    public TSchoolCertificateDocument.Subjects createTSchoolCertificateDocumentSubjects() {
        return new TSchoolCertificateDocument.Subjects();
    }

    /**
     * Create an instance of {@link TSportDocument }
     * 
     */
    public TSportDocument createTSportDocument() {
        return new TSportDocument();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.EntranceTestResults.EntranceTestResult.IsDisabled }
     * 
     */
    public PackageData.Applications.Application.EntranceTestResults.EntranceTestResult.IsDisabled createPackageDataApplicationsApplicationEntranceTestResultsEntranceTestResultIsDisabled() {
        return new PackageData.Applications.Application.EntranceTestResults.EntranceTestResult.IsDisabled();
    }

    /**
     * Create an instance of {@link TMiddleEduDiplomaDocument }
     * 
     */
    public TMiddleEduDiplomaDocument createTMiddleEduDiplomaDocument() {
        return new TMiddleEduDiplomaDocument();
    }

    /**
     * Create an instance of {@link PackageData.Orders.Applications.Application }
     * 
     */
    public PackageData.Orders.Applications.Application createPackageDataOrdersApplicationsApplication() {
        return new PackageData.Orders.Applications.Application();
    }

    /**
     * Create an instance of {@link PackageData.Orders }
     * 
     */
    public PackageData.Orders createPackageDataOrders() {
        return new PackageData.Orders();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link TSchoolCertificateDocument }
     * 
     */
    public TSchoolCertificateDocument createTSchoolCertificateDocument() {
        return new TSchoolCertificateDocument();
    }

    /**
     * Create an instance of {@link PackageData.Orders.OrdersOfException.OrderOfException }
     * 
     */
    public PackageData.Orders.OrdersOfException.OrderOfException createPackageDataOrdersOrdersOfExceptionOrderOfException() {
        return new PackageData.Orders.OrdersOfException.OrderOfException();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.GiaDocuments.GiaDocument.Subjects }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.GiaDocuments.GiaDocument.Subjects createPackageDataApplicationsApplicationApplicationDocumentsGiaDocumentsGiaDocumentSubjects() {
        return new PackageData.Applications.Application.ApplicationDocuments.GiaDocuments.GiaDocument.Subjects();
    }

    /**
     * Create an instance of {@link TPhDDiplomaDocument }
     * 
     */
    public TPhDDiplomaDocument createTPhDDiplomaDocument() {
        return new TPhDDiplomaDocument();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupCommonBenefitCommonBenefitItem() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationCommonBenefits.ApplicationCommonBenefit }
     * 
     */
    public PackageData.Applications.Application.ApplicationCommonBenefits.ApplicationCommonBenefit createPackageDataApplicationsApplicationApplicationCommonBenefitsApplicationCommonBenefit() {
        return new PackageData.Applications.Application.ApplicationCommonBenefits.ApplicationCommonBenefit();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.MinEgeMarks.MinMarks }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.MinEgeMarks.MinMarks createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupCommonBenefitCommonBenefitItemMinEgeMarksMinMarks() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.MinEgeMarks.MinMarks();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo }
     * 
     */
    public PackageData.AdmissionInfo createPackageDataAdmissionInfo() {
        return new PackageData.AdmissionInfo();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupEntranceTestItemsEntranceTestItemEntranceTestBenefits() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.Entrant }
     * 
     */
    public PackageData.Applications.Application.Entrant createPackageDataApplicationsApplicationEntrant() {
        return new PackageData.Applications.Application.Entrant();
    }

    /**
     * Create an instance of {@link THighEduDiplomaDocument }
     * 
     */
    public THighEduDiplomaDocument createTHighEduDiplomaDocument() {
        return new THighEduDiplomaDocument();
    }

    /**
     * Create an instance of {@link Root.AuthData }
     * 
     */
    public Root.AuthData createRootAuthData() {
        return new Root.AuthData();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.EgeDocuments.EgeDocument.Subjects.SubjectData }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.EgeDocuments.EgeDocument.Subjects.SubjectData createPackageDataApplicationsApplicationApplicationDocumentsEgeDocumentsEgeDocumentSubjectsSubjectData() {
        return new PackageData.Applications.Application.ApplicationDocuments.EgeDocuments.EgeDocument.Subjects.SubjectData();
    }

    /**
     * Create an instance of {@link PackageData.InstitutionAchievements.InstitutionAchievement }
     * 
     */
    public PackageData.InstitutionAchievements.InstitutionAchievement createPackageDataInstitutionAchievementsInstitutionAchievement() {
        return new PackageData.InstitutionAchievements.InstitutionAchievement();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.ProfileForAllOlympics }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.ProfileForAllOlympics createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupCommonBenefitCommonBenefitItemProfileForAllOlympics() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.ProfileForAllOlympics();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.OrphanDocuments }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.OrphanDocuments createPackageDataApplicationsApplicationApplicationDocumentsOrphanDocuments() {
        return new PackageData.Applications.Application.ApplicationDocuments.OrphanDocuments();
    }

    /**
     * Create an instance of {@link PackageData.Orders.OrdersOfAdmission }
     * 
     */
    public PackageData.Orders.OrdersOfAdmission createPackageDataOrdersOrdersOfAdmission() {
        return new PackageData.Orders.OrdersOfAdmission();
    }

    /**
     * Create an instance of {@link PackageData.CampaignInfo }
     * 
     */
    public PackageData.CampaignInfo createPackageDataCampaignInfo() {
        return new PackageData.CampaignInfo();
    }

    /**
     * Create an instance of {@link PackageData.Orders.Applications }
     * 
     */
    public PackageData.Orders.Applications createPackageDataOrdersApplications() {
        return new PackageData.Orders.Applications();
    }

    /**
     * Create an instance of {@link TIncomplHighEduDiplomaDocument }
     * 
     */
    public TIncomplHighEduDiplomaDocument createTIncomplHighEduDiplomaDocument() {
        return new TIncomplHighEduDiplomaDocument();
    }

    /**
     * Create an instance of {@link PackageData.CampaignInfo.Campaigns.Campaign.EducationLevels }
     * 
     */
    public PackageData.CampaignInfo.Campaigns.Campaign.EducationLevels createPackageDataCampaignInfoCampaignsCampaignEducationLevels() {
        return new PackageData.CampaignInfo.Campaigns.Campaign.EducationLevels();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.FinSourceAndEduForms }
     * 
     */
    public PackageData.Applications.Application.FinSourceAndEduForms createPackageDataApplicationsApplicationFinSourceAndEduForms() {
        return new PackageData.Applications.Application.FinSourceAndEduForms();
    }

    /**
     * Create an instance of {@link PackageData.CampaignInfo.Campaigns.Campaign }
     * 
     */
    public PackageData.CampaignInfo.Campaigns.Campaign createPackageDataCampaignInfoCampaignsCampaign() {
        return new PackageData.CampaignInfo.Campaigns.Campaign();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments createPackageDataApplicationsApplicationApplicationDocuments() {
        return new PackageData.Applications.Application.ApplicationDocuments();
    }

    /**
     * Create an instance of {@link PackageData.Applications }
     * 
     */
    public PackageData.Applications createPackageDataApplications() {
        return new PackageData.Applications();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.EntranceTestResults.EntranceTestResult }
     * 
     */
    public PackageData.Applications.Application.EntranceTestResults.EntranceTestResult createPackageDataApplicationsApplicationEntranceTestResultsEntranceTestResult() {
        return new PackageData.Applications.Application.EntranceTestResults.EntranceTestResult();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.OlympicDiplomTypes }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.OlympicDiplomTypes createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupCommonBenefitCommonBenefitItemOlympicDiplomTypes() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.OlympicDiplomTypes();
    }

    /**
     * Create an instance of {@link TEgeDocumentSubject }
     * 
     */
    public TEgeDocumentSubject createTEgeDocumentSubject() {
        return new TEgeDocumentSubject();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.GiaDocuments.GiaDocument }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.GiaDocuments.GiaDocument createPackageDataApplicationsApplicationApplicationDocumentsGiaDocumentsGiaDocument() {
        return new PackageData.Applications.Application.ApplicationDocuments.GiaDocuments.GiaDocument();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.EgeDocuments }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.EgeDocuments createPackageDataApplicationsApplicationApplicationDocumentsEgeDocuments() {
        return new PackageData.Applications.Application.ApplicationDocuments.EgeDocuments();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.GiaDocuments }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.GiaDocuments createPackageDataApplicationsApplicationApplicationDocumentsGiaDocuments() {
        return new PackageData.Applications.Application.ApplicationDocuments.GiaDocuments();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.ProfileForAllOlympics }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.ProfileForAllOlympics createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupEntranceTestItemsEntranceTestItemEntranceTestBenefitsEntranceTestBenefitItemProfileForAllOlympics() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.ProfileForAllOlympics();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.Entrant.EmailOrMailAddress }
     * 
     */
    public PackageData.Applications.Application.Entrant.EmailOrMailAddress createPackageDataApplicationsApplicationEntrantEmailOrMailAddress() {
        return new PackageData.Applications.Application.Entrant.EmailOrMailAddress();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.OlympicsLevels.Olympic.Profiles }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.OlympicsLevels.Olympic.Profiles createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupCommonBenefitCommonBenefitItemOlympicsLevelsOlympicProfiles() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.OlympicsLevels.Olympic.Profiles();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupCommonBenefit() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit();
    }

    /**
     * Create an instance of {@link PackageData.Orders.OrdersOfException }
     * 
     */
    public PackageData.Orders.OrdersOfException createPackageDataOrdersOrdersOfException() {
        return new PackageData.Orders.OrdersOfException();
    }

    /**
     * Create an instance of {@link TAcademicDiplomaDocument }
     * 
     */
    public TAcademicDiplomaDocument createTAcademicDiplomaDocument() {
        return new TAcademicDiplomaDocument();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.MilitaryCardDocument }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.MilitaryCardDocument createPackageDataApplicationsApplicationApplicationDocumentsMilitaryCardDocument() {
        return new PackageData.Applications.Application.ApplicationDocuments.MilitaryCardDocument();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationCommonBenefits.ApplicationCommonBenefit.DocumentReason.MedicalDocuments.BenefitDocument }
     * 
     */
    public PackageData.Applications.Application.ApplicationCommonBenefits.ApplicationCommonBenefit.DocumentReason.MedicalDocuments.BenefitDocument createPackageDataApplicationsApplicationApplicationCommonBenefitsApplicationCommonBenefitDocumentReasonMedicalDocumentsBenefitDocument() {
        return new PackageData.Applications.Application.ApplicationCommonBenefits.ApplicationCommonBenefit.DocumentReason.MedicalDocuments.BenefitDocument();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.AdmissionVolume.Item }
     * 
     */
    public PackageData.AdmissionInfo.AdmissionVolume.Item createPackageDataAdmissionInfoAdmissionVolumeItem() {
        return new PackageData.AdmissionInfo.AdmissionVolume.Item();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.StudentDocument }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.StudentDocument createPackageDataApplicationsApplicationApplicationDocumentsStudentDocument() {
        return new PackageData.Applications.Application.ApplicationDocuments.StudentDocument();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupEntranceTestItemsEntranceTestItemEntranceTestBenefitsEntranceTestBenefitItem() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem();
    }

    /**
     * Create an instance of {@link TOrphanDocument }
     * 
     */
    public TOrphanDocument createTOrphanDocument() {
        return new TOrphanDocument();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.IdentityDocument }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.IdentityDocument createPackageDataApplicationsApplicationApplicationDocumentsIdentityDocument() {
        return new PackageData.Applications.Application.ApplicationDocuments.IdentityDocument();
    }

    /**
     * Create an instance of {@link TPostGraduateDiplomaDocument }
     * 
     */
    public TPostGraduateDiplomaDocument createTPostGraduateDiplomaDocument() {
        return new TPostGraduateDiplomaDocument();
    }

    /**
     * Create an instance of {@link TUkraineOlympic }
     * 
     */
    public TUkraineOlympic createTUkraineOlympic() {
        return new TUkraineOlympic();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.OlympicsLevels }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.OlympicsLevels createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupEntranceTestItemsEntranceTestItemEntranceTestBenefitsEntranceTestBenefitItemOlympicsLevels() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.OlympicsLevels();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.DistributedAdmissionVolume.Item }
     * 
     */
    public PackageData.AdmissionInfo.DistributedAdmissionVolume.Item createPackageDataAdmissionInfoDistributedAdmissionVolumeItem() {
        return new PackageData.AdmissionInfo.DistributedAdmissionVolume.Item();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.MinEgeMarks }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.MinEgeMarks createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupCommonBenefitCommonBenefitItemMinEgeMarks() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.MinEgeMarks();
    }

    /**
     * Create an instance of {@link TDisabilityDocument }
     * 
     */
    public TDisabilityDocument createTDisabilityDocument() {
        return new TDisabilityDocument();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups createPackageDataAdmissionInfoCompetitiveGroups() {
        return new PackageData.AdmissionInfo.CompetitiveGroups();
    }

    /**
     * Create an instance of {@link TEduCustomDocument }
     * 
     */
    public TEduCustomDocument createTEduCustomDocument() {
        return new TEduCustomDocument();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.CustomDocuments }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.CustomDocuments createPackageDataApplicationsApplicationApplicationDocumentsCustomDocuments() {
        return new PackageData.Applications.Application.ApplicationDocuments.CustomDocuments();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.Entrant.IsFromKrym }
     * 
     */
    public PackageData.Applications.Application.Entrant.IsFromKrym createPackageDataApplicationsApplicationEntrantIsFromKrym() {
        return new PackageData.Applications.Application.Entrant.IsFromKrym();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application }
     * 
     */
    public PackageData.Applications.Application createPackageDataApplicationsApplication() {
        return new PackageData.Applications.Application();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.Olympics }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.Olympics createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupCommonBenefitCommonBenefitItemOlympics() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.Olympics();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationCommonBenefits.ApplicationCommonBenefit.DocumentReason }
     * 
     */
    public PackageData.Applications.Application.ApplicationCommonBenefits.ApplicationCommonBenefit.DocumentReason createPackageDataApplicationsApplicationApplicationCommonBenefitsApplicationCommonBenefitDocumentReason() {
        return new PackageData.Applications.Application.ApplicationCommonBenefits.ApplicationCommonBenefit.DocumentReason();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.EntranceTestResults.EntranceTestResult.IsDistant }
     * 
     */
    public PackageData.Applications.Application.EntranceTestResults.EntranceTestResult.IsDistant createPackageDataApplicationsApplicationEntranceTestResultsEntranceTestResultIsDistant() {
        return new PackageData.Applications.Application.EntranceTestResults.EntranceTestResult.IsDistant();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.FinSourceAndEduForms.FinSourceEduForm }
     * 
     */
    public PackageData.Applications.Application.FinSourceAndEduForms.FinSourceEduForm createPackageDataApplicationsApplicationFinSourceAndEduFormsFinSourceEduForm() {
        return new PackageData.Applications.Application.FinSourceAndEduForms.FinSourceEduForm();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.AdmissionVolume }
     * 
     */
    public PackageData.AdmissionInfo.AdmissionVolume createPackageDataAdmissionInfoAdmissionVolume() {
        return new PackageData.AdmissionInfo.AdmissionVolume();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.SportDocuments }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.SportDocuments createPackageDataApplicationsApplicationApplicationDocumentsSportDocuments() {
        return new PackageData.Applications.Application.ApplicationDocuments.SportDocuments();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationCommonBenefits.ApplicationCommonBenefit.DocumentReason.MedicalDocuments }
     * 
     */
    public PackageData.Applications.Application.ApplicationCommonBenefits.ApplicationCommonBenefit.DocumentReason.MedicalDocuments createPackageDataApplicationsApplicationApplicationCommonBenefitsApplicationCommonBenefitDocumentReasonMedicalDocuments() {
        return new PackageData.Applications.Application.ApplicationCommonBenefits.ApplicationCommonBenefit.DocumentReason.MedicalDocuments();
    }

    /**
     * Create an instance of {@link TCompatriotDocument }
     * 
     */
    public TCompatriotDocument createTCompatriotDocument() {
        return new TCompatriotDocument();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.Olympics }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.Olympics createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupEntranceTestItemsEntranceTestItemEntranceTestBenefitsEntranceTestBenefitItemOlympics() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.Olympics();
    }

    /**
     * Create an instance of {@link TInternationalOlympic }
     * 
     */
    public TInternationalOlympic createTInternationalOlympic() {
        return new TInternationalOlympic();
    }

    /**
     * Create an instance of {@link TEntranceTestSubject }
     * 
     */
    public TEntranceTestSubject createTEntranceTestSubject() {
        return new TEntranceTestSubject();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.CompatriotDocuments }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.CompatriotDocuments createPackageDataApplicationsApplicationApplicationDocumentsCompatriotDocuments() {
        return new PackageData.Applications.Application.ApplicationDocuments.CompatriotDocuments();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.OlympicDiplomTypes }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.OlympicDiplomTypes createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupEntranceTestItemsEntranceTestItemEntranceTestBenefitsEntranceTestBenefitItemOlympicDiplomTypes() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.OlympicDiplomTypes();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.EduDocuments.EduDocument }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.EduDocuments.EduDocument createPackageDataApplicationsApplicationApplicationDocumentsEduDocumentsEduDocument() {
        return new PackageData.Applications.Application.ApplicationDocuments.EduDocuments.EduDocument();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroup() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup();
    }

    /**
     * Create an instance of {@link TMedicalDocument }
     * 
     */
    public TMedicalDocument createTMedicalDocument() {
        return new TMedicalDocument();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.TargetOrganizations.TargetOrganization }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.TargetOrganizations.TargetOrganization createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupTargetOrganizationsTargetOrganization() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.TargetOrganizations.TargetOrganization();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.OlympicsLevels }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.OlympicsLevels createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupCommonBenefitCommonBenefitItemOlympicsLevels() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.OlympicsLevels();
    }

    /**
     * Create an instance of {@link TInstitutionDocument }
     * 
     */
    public TInstitutionDocument createTInstitutionDocument() {
        return new TInstitutionDocument();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.EntranceTestResults }
     * 
     */
    public PackageData.Applications.Application.EntranceTestResults createPackageDataApplicationsApplicationEntranceTestResults() {
        return new PackageData.Applications.Application.EntranceTestResults();
    }

    /**
     * Create an instance of {@link PackageData.TargetOrganizations.TargetOrganization }
     * 
     */
    public PackageData.TargetOrganizations.TargetOrganization createPackageDataTargetOrganizationsTargetOrganization() {
        return new PackageData.TargetOrganizations.TargetOrganization();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EduPrograms.EduProgram }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EduPrograms.EduProgram createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupEduProgramsEduProgram() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EduPrograms.EduProgram();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.Entrant.EmailOrMailAddress.MailAddress }
     * 
     */
    public PackageData.Applications.Application.Entrant.EmailOrMailAddress.MailAddress createPackageDataApplicationsApplicationEntrantEmailOrMailAddressMailAddress() {
        return new PackageData.Applications.Application.Entrant.EmailOrMailAddress.MailAddress();
    }

    /**
     * Create an instance of {@link PackageData.CampaignInfo.Campaigns.Campaign.EducationForms }
     * 
     */
    public PackageData.CampaignInfo.Campaigns.Campaign.EducationForms createPackageDataCampaignInfoCampaignsCampaignEducationForms() {
        return new PackageData.CampaignInfo.Campaigns.Campaign.EducationForms();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.OtherIdentityDocuments.IdentityDocument }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.OtherIdentityDocuments.IdentityDocument createPackageDataApplicationsApplicationApplicationDocumentsOtherIdentityDocumentsIdentityDocument() {
        return new PackageData.Applications.Application.ApplicationDocuments.OtherIdentityDocuments.IdentityDocument();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupEntranceTestItemsEntranceTestItem() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.TargetOrganizations }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.TargetOrganizations createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupTargetOrganizations() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.TargetOrganizations();
    }

    /**
     * Create an instance of {@link TCustomDocument }
     * 
     */
    public TCustomDocument createTCustomDocument() {
        return new TCustomDocument();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.GiaDocuments.GiaDocument.Subjects.SubjectData }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.GiaDocuments.GiaDocument.Subjects.SubjectData createPackageDataApplicationsApplicationApplicationDocumentsGiaDocumentsGiaDocumentSubjectsSubjectData() {
        return new PackageData.Applications.Application.ApplicationDocuments.GiaDocuments.GiaDocument.Subjects.SubjectData();
    }

    /**
     * Create an instance of {@link PackageData.Orders.OrdersOfAdmission.OrderOfAdmission }
     * 
     */
    public PackageData.Orders.OrdersOfAdmission.OrderOfAdmission createPackageDataOrdersOrdersOfAdmissionOrderOfAdmission() {
        return new PackageData.Orders.OrdersOfAdmission.OrderOfAdmission();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.IndividualAchievements }
     * 
     */
    public PackageData.Applications.Application.IndividualAchievements createPackageDataApplicationsApplicationIndividualAchievements() {
        return new PackageData.Applications.Application.IndividualAchievements();
    }

    /**
     * Create an instance of {@link TBasicDiplomaDocument }
     * 
     */
    public TBasicDiplomaDocument createTBasicDiplomaDocument() {
        return new TBasicDiplomaDocument();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EduPrograms }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EduPrograms createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupEduPrograms() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EduPrograms();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.EgeDocuments.EgeDocument }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.EgeDocuments.EgeDocument createPackageDataApplicationsApplicationApplicationDocumentsEgeDocumentsEgeDocument() {
        return new PackageData.Applications.Application.ApplicationDocuments.EgeDocuments.EgeDocument();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupEntranceTestItems() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CompetitiveGroupItem }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CompetitiveGroupItem createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupCompetitiveGroupItem() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CompetitiveGroupItem();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.EgeDocuments.EgeDocument.Subjects }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.EgeDocuments.EgeDocument.Subjects createPackageDataApplicationsApplicationApplicationDocumentsEgeDocumentsEgeDocumentSubjects() {
        return new PackageData.Applications.Application.ApplicationDocuments.EgeDocuments.EgeDocument.Subjects();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.DistributedAdmissionVolume }
     * 
     */
    public PackageData.AdmissionInfo.DistributedAdmissionVolume createPackageDataAdmissionInfoDistributedAdmissionVolume() {
        return new PackageData.AdmissionInfo.DistributedAdmissionVolume();
    }

    /**
     * Create an instance of {@link TOlympicDocument }
     * 
     */
    public TOlympicDocument createTOlympicDocument() {
        return new TOlympicDocument();
    }

    /**
     * Create an instance of {@link TSchoolCertificateDocument.Subjects.SubjectData }
     * 
     */
    public TSchoolCertificateDocument.Subjects.SubjectData createTSchoolCertificateDocumentSubjectsSubjectData() {
        return new TSchoolCertificateDocument.Subjects.SubjectData();
    }

    /**
     * Create an instance of {@link PackageData.InstitutionAchievements }
     * 
     */
    public PackageData.InstitutionAchievements createPackageDataInstitutionAchievements() {
        return new PackageData.InstitutionAchievements();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.OlympicsLevels.Olympic.Profiles }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.OlympicsLevels.Olympic.Profiles createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupEntranceTestItemsEntranceTestItemEntranceTestBenefitsEntranceTestBenefitItemOlympicsLevelsOlympicProfiles() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.EntranceTestBenefits.EntranceTestBenefitItem.OlympicsLevels.Olympic.Profiles();
    }

    /**
     * Create an instance of {@link PackageData.CampaignInfo.Campaigns }
     * 
     */
    public PackageData.CampaignInfo.Campaigns createPackageDataCampaignInfoCampaigns() {
        return new PackageData.CampaignInfo.Campaigns();
    }

    /**
     * Create an instance of {@link PackageData }
     * 
     */
    public PackageData createPackageData() {
        return new PackageData();
    }

    /**
     * Create an instance of {@link TAllowEducationDocument }
     * 
     */
    public TAllowEducationDocument createTAllowEducationDocument() {
        return new TAllowEducationDocument();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.IsForSPOandVO }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.IsForSPOandVO createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupEntranceTestItemsEntranceTestItemIsForSPOandVO() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.EntranceTestItems.EntranceTestItem.IsForSPOandVO();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.IndividualAchievements.IndividualAchievement }
     * 
     */
    public PackageData.Applications.Application.IndividualAchievements.IndividualAchievement createPackageDataApplicationsApplicationIndividualAchievementsIndividualAchievement() {
        return new PackageData.Applications.Application.IndividualAchievements.IndividualAchievement();
    }

    /**
     * Create an instance of {@link TOlympicTotalDocument }
     * 
     */
    public TOlympicTotalDocument createTOlympicTotalDocument() {
        return new TOlympicTotalDocument();
    }

    /**
     * Create an instance of {@link PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.OlympicsLevels.Olympic }
     * 
     */
    public PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.OlympicsLevels.Olympic createPackageDataAdmissionInfoCompetitiveGroupsCompetitiveGroupCommonBenefitCommonBenefitItemOlympicsLevelsOlympic() {
        return new PackageData.AdmissionInfo.CompetitiveGroups.CompetitiveGroup.CommonBenefit.CommonBenefitItem.OlympicsLevels.Olympic();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationDocuments.OtherIdentityDocuments }
     * 
     */
    public PackageData.Applications.Application.ApplicationDocuments.OtherIdentityDocuments createPackageDataApplicationsApplicationApplicationDocumentsOtherIdentityDocuments() {
        return new PackageData.Applications.Application.ApplicationDocuments.OtherIdentityDocuments();
    }

    /**
     * Create an instance of {@link PackageData.Applications.Application.ApplicationCommonBenefits }
     * 
     */
    public PackageData.Applications.Application.ApplicationCommonBenefits createPackageDataApplicationsApplicationApplicationCommonBenefits() {
        return new PackageData.Applications.Application.ApplicationCommonBenefits();
    }

}
