//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.13 at 12:57:22 PM GMT+03:00 
//


package abit.paket;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TInternationalOlympic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TInternationalOlympic">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="UID" type="{}TUID"/>
 *         &lt;element name="OriginalReceivedDate" type="{}TDate" minOccurs="0"/>
 *         &lt;element name="DocumentSeries" type="{}TDocumentSeries" minOccurs="0"/>
 *         &lt;element name="DocumentNumber" type="{}TDocumentNumber"/>
 *         &lt;element name="CountryID" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="OlympicName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OlympicProfile" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OlympicDate" type="{}TDate" minOccurs="0"/>
 *         &lt;element name="OlympicPlace" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TInternationalOlympic", propOrder = {

})
public class TInternationalOlympic {

    @XmlElement(name = "UID", required = true)
    protected String uid;
    @XmlElement(name = "OriginalReceivedDate")
    protected XMLGregorianCalendar originalReceivedDate;
    @XmlElement(name = "DocumentSeries")
    protected String documentSeries;
    @XmlElement(name = "DocumentNumber", required = true)
    protected String documentNumber;
    @XmlElement(name = "CountryID")
    @XmlSchemaType(name = "unsignedInt")
    protected long countryID;
    @XmlElement(name = "OlympicName", required = true)
    protected String olympicName;
    @XmlElement(name = "OlympicProfile")
    protected String olympicProfile;
    @XmlElement(name = "OlympicDate")
    protected XMLGregorianCalendar olympicDate;
    @XmlElement(name = "OlympicPlace")
    protected String olympicPlace;

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUID() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUID(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the originalReceivedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOriginalReceivedDate() {
        return originalReceivedDate;
    }

    /**
     * Sets the value of the originalReceivedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOriginalReceivedDate(XMLGregorianCalendar value) {
        this.originalReceivedDate = value;
    }

    /**
     * Gets the value of the documentSeries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentSeries() {
        return documentSeries;
    }

    /**
     * Sets the value of the documentSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentSeries(String value) {
        this.documentSeries = value;
    }

    /**
     * Gets the value of the documentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentNumber() {
        return documentNumber;
    }

    /**
     * Sets the value of the documentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentNumber(String value) {
        this.documentNumber = value;
    }

    /**
     * Gets the value of the countryID property.
     * 
     */
    public long getCountryID() {
        return countryID;
    }

    /**
     * Sets the value of the countryID property.
     * 
     */
    public void setCountryID(long value) {
        this.countryID = value;
    }

    /**
     * Gets the value of the olympicName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOlympicName() {
        return olympicName;
    }

    /**
     * Sets the value of the olympicName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOlympicName(String value) {
        this.olympicName = value;
    }

    /**
     * Gets the value of the olympicProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOlympicProfile() {
        return olympicProfile;
    }

    /**
     * Sets the value of the olympicProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOlympicProfile(String value) {
        this.olympicProfile = value;
    }

    /**
     * Gets the value of the olympicDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOlympicDate() {
        return olympicDate;
    }

    /**
     * Sets the value of the olympicDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOlympicDate(XMLGregorianCalendar value) {
        this.olympicDate = value;
    }

    /**
     * Gets the value of the olympicPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOlympicPlace() {
        return olympicPlace;
    }

    /**
     * Sets the value of the olympicPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOlympicPlace(String value) {
        this.olympicPlace = value;
    }

}
